# Generated by Django 3.0.4 on 2020-03-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validated_email',
            field=models.BooleanField(default=False),
        ),
    ]
