# Generated by Django 3.0.4 on 2020-03-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['plz']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
