# Generated by Django 3.0.4 on 2020-03-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Diverse')])),
                ('age', models.IntegerField(choices=[(1, '10-19'), (2, '20-29'), (3, '30-39'), (4, '40-49'), (5, '50-59'), (6, '60-69'), (7, '>70')])),
                ('my_field_name', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
