# Generated by Django 3.0.4 on 2020-03-21 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0002_auto_20200321_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berufsausbildung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arzt', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('krankenpflege', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('pflegehilfe', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('anaesthesiepflege', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('intensivpflege', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ota', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('mfa', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('mta_lta', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('rta', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('arztapprobation', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('rettungssanitaeter', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('plfegeausbildung', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('op_pflege', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('op_assistenz', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('kinderbetreuung', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('hebamme', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('sprechstundenhilfe', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('fsj_krankenhaus', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('famulatur', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('psychologie', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('labortechnische_assistenz', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='my_field_name',
        ),
        migrations.AddField(
            model_name='student',
            name='availability_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='availability_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='availability_weekdays_friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='availability_weekdays_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='availability_weekdays_saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='availability_weekdays_sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='availability_weekdays_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='availability_weekdays_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='availability_weekdays_wednesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='availability_weekhours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='berufserfahrung_monate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='braucht_bezahlung',
            field=models.IntegerField(choices=[(1, 'Keine'), (2, 'Minijob'), (3, 'Vollzeit')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='famulaturreife',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='immatrikuliert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='m2absolviert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='plz',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='vorfrage_covidkontakt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='vorfrage_erkaeltung',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='vorfrage_risikogebiet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='vorfrage_symptome',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='vorfrage_vorerkrankungen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(choices=[(1, '10-19'), (2, '20-29'), (3, '30-39'), (4, '40-49'), (5, '50-59'), (6, '60-69'), (7, '>70')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Diverse')], default=3),
        ),
        migrations.AddField(
            model_name='student',
            name='berufsausbildung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iamstudent.Berufsausbildung'),
        ),
    ]
