# Generated by Django 3.0.4 on 2020-03-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0003_auto_20200324_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
