# Generated by Django 3.0.4 on 2020-03-21 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0003_auto_20200321_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='berufsausbildung',
        ),
        migrations.AddField(
            model_name='student',
            name='ba_anaesthesiepflege',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_arzt',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_arztapprobation',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_famulatur',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_fsj_krankenhaus',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_hebamme',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_intensivpflege',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_kinderbetreuung',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_krankenpflege',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_labortechnische_assistenz',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_mfa',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_mta_lta',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_op_assistenz',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_op_pflege',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_ota',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_pflegehilfe',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_plfegeausbildung',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_psychologie',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_rettungssanitaeter',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_rta',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ba_sprechstundenhilfe',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.DeleteModel(
            name='Berufsausbildung',
        ),
    ]
