# Generated by Django 3.0.4 on 2020-03-21 17:30

from django.db import migrations, models
import iamstudent.models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0004_auto_20200321_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='availability_end',
        ),
        migrations.RemoveField(
            model_name='student',
            name='availability_weekdays_friday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='availability_weekdays_monday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='availability_weekdays_saturday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='availability_weekdays_sunday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='availability_weekdays_thursday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='availability_weekdays_tuesday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='availability_weekdays_wednesday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='availability_weekhours',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorfrage_covidkontakt',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorfrage_erkaeltung',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorfrage_risikogebiet',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorfrage_symptome',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorfrage_vorerkrankungen',
        ),
        migrations.AlterField(
            model_name='student',
            name='plz',
            field=models.IntegerField(null=True, validators=[iamstudent.models.validate_plz]),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(null=True, validators=[iamstudent.models.validate_semester]),
        ),
    ]
