# Generated by Django 3.0.4 on 2020-03-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0005_auto_20200321_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
