# Generated by Django 3.0.4 on 2020-03-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0006_auto_20200321_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ba_arztapprobation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ba_op_assistenz',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ba_op_pflege',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ba_plfegeausbildung',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ba_psychologie',
        ),
        migrations.RemoveField(
            model_name='student',
            name='berufserfahrung_monate',
        ),
        migrations.AddField(
            model_name='student',
            name='ba_pflegepraktika',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_abstriche',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_anrufe',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_arztbriefeschreiben',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_beatmungsgerätebedienen',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_bgas',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_blutentnahmedienst',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_blutkulturenabnehmen',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_coronascreening',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_drkblutspende',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_edvkenntnisse',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_ekgschreiben',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_hotline',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_infektionsnachverfolgung',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_infusionenmischen',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_kinderbetreuung',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_labortätigkeiten',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_opassistenz',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_patientenaufnahme',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_patientenlagerung',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_patientenpflege',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_pflegeunterstuetzung',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_transportdienst',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_ultraschall',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_zugaengelegen',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='ba_famulatur',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='ba_fsj_krankenhaus',
            field=models.CharField(default='', max_length=100),
        ),
    ]
