# Generated by Django 3.0.4 on 2020-03-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0007_auto_20200321_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='berufserfahrung_monate',
            field=models.IntegerField(null=True),
        ),
    ]
