# Generated by Django 3.0.4 on 2020-03-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0007_auto_20200325_0126'),
        ('iamstudent', '0005_emailtosend'),
    ]

    operations = [
    ]
