# Generated by Django 3.0.4 on 2020-03-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0008_student_berufserfahrung_monate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ba_famulatur',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='ba_fsj_krankenhaus',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='ba_pflegepraktika',
            field=models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1),
        ),
    ]
