# Generated by Django 3.0.4 on 2020-03-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0010_auto_20200322_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='berufserfahrung_monate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='famulaturreife',
        ),
        migrations.RemoveField(
            model_name='student',
            name='m2absolviert',
        ),
    ]
