# Generated by Django 3.0.4 on 2020-03-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0011_auto_20200322_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
