# Generated by Django 3.0.4 on 2020-03-22 17:55

from django.db import migrations, models
import iamstudent.models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0014_auto_20200322_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='plz',
            field=models.CharField(max_length=5, null=True, validators=[iamstudent.models.validate_plz]),
        ),
    ]
