# Generated by Django 3.0.4 on 2020-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
