# Generated by Django 3.0.4 on 2020-04-09 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_validation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 17, 0, 13, 584288)),
        ),
    ]
