# Generated by Django 3.0.5 on 2020-04-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_custom_migration_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
