# Generated by Django 3.0.4 on 2020-04-10 21:13

import datetime
import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import apps.accounts.user


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_custom_migration_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterApprovedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_code', models.IntegerField(default=apps.accounts.newsletter_approved_by.random_number)),
                ('did_see_email', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_edited_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('frozen_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('send_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='', max_length=1000000)),
                ('was_sent', models.BooleanField(default=False)),
                ('send_to_hospitals', models.BooleanField(default=False)),
                ('send_to_students', models.BooleanField(default=False)),
                ('user_validation_required', models.IntegerField(choices=[(0, 'validierte'), (1, 'nicht validierte'), (2, 'varlidierte und nicht validierte')], default=0)),
                ('frozen_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_by', to=settings.AUTH_USER_MODEL)),
                ('letter_approved_by', models.ManyToManyField(related_name='letter_approved_by', through='accounts.LetterApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('letter_authored_by', models.ManyToManyField(related_name='letter_authored_by', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='letterapprovedby',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Newsletter'),
        ),
        migrations.AddField(
            model_name='letterapprovedby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='letterapprovedby',
            unique_together={('user', 'newsletter')},
        ),
    ]
