# Generated by Django 3.0.5 on 2020-04-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200410_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='user_validation_required',
            field=models.IntegerField(choices=[(0, 'validierte'), (1, 'nicht validierte'), (2, 'varlidierte und nicht validierte'), (3, 'validiert und von uns approved')], default=0),
        ),
    ]
