# Generated by Django 3.0.4 on 2020-03-24 07:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iamstudent.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sonstige_infos', models.TextField(default='')),
                ('ansprechpartner', models.CharField(default='', max_length=100)),
                ('telefon', models.CharField(default='', max_length=100)),
                ('firmenname', models.CharField(default='', max_length=100)),
                ('plz', models.CharField(max_length=5, null=True, validators=[iamstudent.models.validate_plz])),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
