# Generated by Django 3.0.4 on 2020-03-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ineedstudent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='firmenname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='telefon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
