# Generated by Django 3.0.4 on 2020-03-22 18:38

from django.db import migrations, models
import iamstudent.models


class Migration(migrations.Migration):

    dependencies = [
        ('ineedstudent', '0003_auto_20200321_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='plz',
            field=models.CharField(max_length=5, null=True, validators=[iamstudent.models.validate_plz]),
        ),
    ]
