# Generated by Django 3.0.4 on 2020-03-26 16:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('countrycode', models.CharField(choices=[('DE', 'Deutschland'), ('AT', 'Österreich')], default='DE', max_length=2)),
                ('sonstige_infos', models.TextField(default='')),
                ('ansprechpartner', models.CharField(default='', max_length=100)),
                ('telefon', models.CharField(default='', max_length=100)),
                ('firmenname', models.CharField(default='', max_length=100)),
                ('plz', models.CharField(max_length=5, null=True)),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('appears_in_map', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['registration_date'],
            },
        ),
    ]
