# Generated by Django 3.0.4 on 2020-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ineedstudent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='max_mails_per_day',
            field=models.IntegerField(default=200),
        ),
    ]
