# Generated by Django 3.0.4 on 2020-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ineedstudent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
