# Generated by Django 3.0.4 on 2020-03-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ineedstudent', '0002_hospital_max_mails_per_day'),
        ('ineedstudent', '0002_auto_20200330_0101'),
    ]

    operations = [
    ]
