# Generated by Django 3.0.4 on 2020-03-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ineedstudent', '0002_auto_20200329_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='sonstige_infos',
        ),
    ]
