# Generated by Django 3.0.4 on 2020-03-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ineedstudent', '0002_hospital_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['registration_date']},
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='email',
        ),
    ]
