# Generated by Django 3.0.4 on 2020-04-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ineedstudent', '0004_auto_20200409_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='sonstige_infos',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
