# Generated by Django 3.0.4 on 2020-03-24 10:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from apps import iamstudent
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('countrycode', models.CharField(choices=[('DE', 'Deutschland'), ('AT', 'Österreich')], default='DE', max_length=2)),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('plz', models.CharField(max_length=5, null=True)),
                ('semester', models.IntegerField(null=True, validators=[iamstudent.models.validate_semester])),
                ('immatrikuliert', models.BooleanField(default=False)),
                ('availability_start', models.DateField(null=True)),
                ('braucht_bezahlung', models.IntegerField(choices=[(1, 'Vergütung Gewünscht aber nicht Notwendig'), (2, 'Minijob'), (3, 'Vollzeit')], default=1)),
                ('ba_arzt', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_krankenpflege', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_pflegehilfe', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_anaesthesiepflege', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_intensivpflege', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_ota', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_mfa', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_mta_lta', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_rta', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_rettungssanitaeter', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_kinderbetreuung', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_hebamme', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_sprechstundenhilfe', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_labortechnische_assistenz', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('ba_famulatur', models.CharField(default='', max_length=100)),
                ('ba_pflegepraktika', models.CharField(default='', max_length=100)),
                ('ba_fsj_krankenhaus', models.CharField(default='', max_length=100)),
                ('skill_coronascreening', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_pflegeunterstuetzung', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_transportdienst', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_kinderbetreuung', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_labortaetigkeiten', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_drkblutspende', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_hotline', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_abstriche', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_patientenpflege', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_patientenlagerung', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_opassistenz', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_blutentnahmedienst', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_anrufe', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_infektionsnachverfolgung', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_patientenaufnahme', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_edvkenntnisse', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_zugaengelegen', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_arztbriefeschreiben', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_blutkulturenabnehmen', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_infusionenmischen', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_ekgschreiben', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_ultraschall', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_bgas', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
                ('skill_beatmungsgeraetebedienen', models.IntegerField(choices=[(1, 'Rot'), (2, 'Gelb'), (3, 'Gruen')], default=1)),
            ],
            options={
                'ordering': ['plz'],
            },
        ),
    ]
