# Generated by Django 3.0.4 on 2020-03-30 00:20

import datetime
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ineedstudent', '0001_initial'),
        ('iamstudent', '0002_auto_20200329_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ausbildung_typ_medstud_abschnitt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Vorklinischer Teil'), (2, 'Klinischer Teil'), (3, 'Praktisches Jahr'), (4, 'Assistenzarzt'), (5, 'Facharzt')], default=0, null=True),
        ),
        migrations.CreateModel(
            name='EmailToHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='')),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ineedstudent.Hospital')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iamstudent.Student')),
            ],
        ),
    ]
