# Generated by Django 3.0.4 on 2020-03-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0003_auto_20200329_1859'),
        ('iamstudent', '0003_auto_20200330_0101'),
    ]

    operations = [
    ]
