# Generated by Django 3.0.4 on 2020-03-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0004_merge_20200330_0124'),
        ('iamstudent', '0004_merge_20200330_0152'),
    ]

    operations = [
    ]
