# Generated by Django 3.0.4 on 2020-03-24 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ineedstudent', '0002_hospital_is_approved'),
        ('iamstudent', '0004_auto_20200324_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='')),
                ('was_sent', models.BooleanField(default=False)),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ineedstudent.Hospital')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iamstudent.Student')),
            ],
        ),
    ]
