# Generated by Django 3.0.4 on 2020-03-30 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0005_student_einwilligung_agb'),
        ('iamstudent', '0005_merge_20200330_0221'),
    ]

    operations = [
    ]
