# Generated by Django 3.0.4 on 2020-03-25 01:19

from django.db import migrations, models
from apps import iamstudent


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0005_auto_20200324_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_arzt_typ',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_arzt_typ_sonstige',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_medstud_abschnitt',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_medstud_anerkennung_noetig',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_medstud_famulaturen_anaesthesie',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_medstud_famulaturen_chirurgie',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_medstud_famulaturen_innere',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_medstud_famulaturen_intensiv',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_medstud_famulaturen_notaufnahme',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_typ',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorausbildung_typ_anaesthesie',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorausbildung_typ_blutentnahmedienst',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorausbildung_typ_fsjgesundheitswesen',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorausbildung_typ_hebamme',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorausbildung_typ_innere',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorausbildung_typ_intensiv',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorausbildung_typ_kinderbetreuung',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorausbildung_typ_krankenpflege',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorausbildung_typ_labor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorausbildung_typ_pflege',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorausbildung_typ_rettungsdienst',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vorausbildung_typ_verwaltunglogistik',
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_arzt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_arzt_sonstige',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_arzt_typ',
            field=models.IntegerField(blank=True, choices=[(1, 'Anästhesie'), (2, 'Chirurgie'), (3, 'Innere Medizin'), (4, 'Intensivstation'), (5, 'Notaufnahme'), (6, 'Andere')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_kinderbetreung',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_kinderbetreung_ausgebildet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_kinderbetreung_vorerfahrung',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_medstud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_medstud_abschnitt',
            field=models.IntegerField(blank=True, choices=[(1, 'Vorklinischer Teil (1.-5. Semester)'), (2, 'Klinischer Teil (6.-10. Semester)'), (3, 'Praktisches Jahr')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_medstud_anerkennung_noetig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_medstud_famulaturen_chirurgie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_medstud_famulaturen_innere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_medstud_famulaturen_intensiv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_medstud_famulaturen_notaufnahme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_medstud_farmulaturen_anaesthesie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_mfa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_mfa_abschnitt',
            field=models.IntegerField(blank=True, choices=[(1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_mta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_mta_abschnitt',
            field=models.IntegerField(blank=True, choices=[(1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_mtla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_mtla_abschnitt',
            field=models.IntegerField(blank=True, choices=[(1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_notfallsani',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_notfallsani_abschnitt',
            field=models.IntegerField(blank=True, choices=[(1, '1. Jahr'), (2, '2. Jahr'), (4, 'Berufstätig')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_sani',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_sonstige_eintragen',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_zahni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_zahni_abschnitt',
            field=models.IntegerField(blank=True, choices=[(1, 'Vorklinischer Teil'), (2, 'Klinischer Teil')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='datenschutz_zugestimmt',
            field=models.BooleanField(default=False, validators=[iamstudent.models.validate_checkbox]),
        ),
        migrations.AddField(
            model_name='student',
            name='einwilligung_datenweitergabe',
            field=models.BooleanField(default=False, validators=[iamstudent.models.validate_checkbox]),
        ),
        migrations.AlterField(
            model_name='student',
            name='ausbildung_typ_sonstige',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='braucht_bezahlung',
            field=models.IntegerField(choices=[(1, 'Ich freue mich über eine Vergütung, helfe aber auch ohne'), (4, 'Ich benötige eine Vergütung')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='umkreis',
            field=models.IntegerField(choices=[(1, '<5 km'), (2, '<10 km'), (3, '<20 km'), (4, '>20 km')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='zeitliche_verfuegbarkeit',
            field=models.IntegerField(choices=[(1, '10h pro Woche'), (2, '20h pro Woche'), (3, '30h pro Woche'), (4, '40h pro Woche')], null=True),
        ),
    ]
