# Generated by Django 3.0.4 on 2020-04-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0006_merge_20200330_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_ata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_ata_abschnitt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_ergotherapie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_ergotherapie_abschnitt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'In Ausbildung'), (2, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_ota',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_ota_abschnitt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_psycho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_psycho_abschnitt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Studium'), (2, 'In Ausbildung'), (3, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentlistfiltermodel',
            name='ausbildung_typ_ata',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='studentlistfiltermodel',
            name='ausbildung_typ_ata_abschnitt_x_gt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentlistfiltermodel',
            name='ausbildung_typ_ata_abschnitt_x_lt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentlistfiltermodel',
            name='ausbildung_typ_ergotherapie',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='studentlistfiltermodel',
            name='ausbildung_typ_ota',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='studentlistfiltermodel',
            name='ausbildung_typ_ota_abschnitt_x_gt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentlistfiltermodel',
            name='ausbildung_typ_ota_abschnitt_x_lt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentlistfiltermodel',
            name='ausbildung_typ_psycho',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='studentlistfiltermodel',
            name='ausbildung_typ_psycho_abschnitt_x_gt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentlistfiltermodel',
            name='ausbildung_typ_psycho_abschnitt_x_lt',
            field=models.IntegerField(default=0),
        ),
    ]
