# Generated by Django 3.0.4 on 2020-04-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0007_auto_20200402_1746'),
        ('iamstudent', '0008_auto_20200402_2211'),
    ]

    operations = [
    ]
