# Generated by Django 3.0.4 on 2020-04-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0010_custom_migration'),
        ('iamstudent', '0009_merge_20200402_2309'),
    ]

    operations = [
    ]
