# Generated by Django 3.0.4 on 2020-03-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0010_auto_20200325_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ausbildung_typ_arzt_sonstige',
            field=models.CharField(blank=True, default='anderer Bereich', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='ausbildung_typ_arzt_typ',
            field=models.IntegerField(choices=[(1, 'Anästhesie'), (2, 'Chirurgie'), (3, 'Innere Medizin'), (4, 'Intensivstation'), (5, 'Notaufnahme'), (0, 'Sonstige')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ausbildung_typ_medstud_abschnitt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Vorklinischer Teil (1.-5. Semester)'), (2, 'Klinischer Teil (6.-10. Semester)'), (3, 'Praktisches Jahr')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ausbildung_typ_sonstige_eintragen',
            field=models.CharField(blank=True, default='keine', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='ausbildung_typ_zahni_abschnitt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Vorklinischer Teil'), (2, 'Klinischer Teil')], default=0, null=True),
        ),
    ]
