# Generated by Django 3.0.5 on 2020-04-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0010_auto_20200405_2217'),
        ('iamstudent', '0011_merge_20200404_2309'),
    ]

    operations = [
    ]
