# Generated by Django 3.0.4 on 2020-03-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0011_auto_20200325_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='umkreis',
            field=models.IntegerField(choices=[(1, '<10 km'), (2, '<20 km'), (3, '<40 km'), (4, '>40 km')], null=True),
        ),
    ]
