# Generated by Django 3.0.4 on 2020-03-26 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ineedstudent', '0004_hospital_appears_in_map'),
        ('iamstudent', '0012_auto_20200325_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ausbildung_typ_arzt',
            new_name='ausbildung_typ_medstud_famulaturen_anaesthesie',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='ausbildung_typ_sonstige_eintragen',
            new_name='sonstige_qualifikationen',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_typ_arzt_sonstige',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_typ_arzt_typ',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_typ_medstud_farmulaturen_anaesthesie',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_typ_sonstige',
        ),
        migrations.AlterField(
            model_name='student',
            name='ausbildung_typ_medstud_abschnitt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Vorklinischer Teil (1.-5. Semester)'), (2, 'Klinischer Teil (6.-10. Semester)'), (3, 'Praktisches Jahr'), (4, 'Assistenzarzt'), (5, 'Facharzt')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ausbildung_typ_zahni_abschnitt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Vorklinischer Teil'), (2, 'Klinischer Teil'), (3, 'Abgeschlossen')], default=0, null=True),
        ),
        migrations.CreateModel(
            name='PersistenStudentFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausbildung_typ_medstud_famulaturen_anaesthesie', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_medstud_famulaturen_chirurgie', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_medstud_famulaturen_innere', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_medstud_famulaturen_intensiv', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_medstud_famulaturen_notaufnahme', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_medstud_anerkennung_noetig', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_medstud_abschnitt', models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Vorklinischer Teil (1.-5. Semester)'), (2, 'Klinischer Teil (6.-10. Semester)'), (3, 'Praktisches Jahr'), (4, 'Assistenzarzt'), (5, 'Facharzt')], default=0, null=True)),
                ('ausbildung_typ_mfa_abschnitt', models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True)),
                ('ausbildung_typ_mtla_abschnitt', models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True)),
                ('ausbildung_typ_mta_abschnitt', models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True)),
                ('ausbildung_typ_notfallsani_abschnitt', models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (4, 'Berufstätig')], default=0, null=True)),
                ('ausbildung_typ_pflege_abschnitt', models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True)),
                ('ausbildung_typ_zahni_abschnitt', models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Vorklinischer Teil'), (2, 'Klinischer Teil'), (3, 'Abgeschlossen')], default=0, null=True)),
                ('ausbildung_typ_physio_abschnitt', models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True)),
                ('ausbildung_typ_kinderbetreung_ausgebildet', models.BooleanField(default=False)),
                ('ausbildung_typ_kinderbetreung_vorerfahrung', models.BooleanField(default=False)),
                ('ausbildung_typ_medstud', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_mfa', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_mtla', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_mta', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_notfallsani', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_pflege', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_sani', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_hebamme', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_fsj', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_zahni', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_physio', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('ausbildung_typ_kinderbetreung', models.CharField(choices=[('unknown', 'egal'), ('true', 'muss')], default='unknown', max_length=10)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ineedstudent.Hospital')),
            ],
        ),
    ]
