# Generated by Django 3.0.4 on 2020-03-26 09:16

import apps.iamstudent.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0013_auto_20200326_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_kinderbetreung_ausgebildet',
        ),
        migrations.RemoveField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_kinderbetreung_vorerfahrung',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_typ_kinderbetreung_ausgebildet',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ausbildung_typ_kinderbetreung_vorerfahrung',
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_kinderbetreung_ausgebildet_abschnitt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Lediglich Erfahrungen'), (2, 'Abgeschlossene Ausbildung')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ausbildung_typ_kinderbetreung_ausgebildet_abschnitt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Lediglich Erfahrungen'), (2, 'Abgeschlossene Ausbildung')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='unterkunft_gewuenscht',
            field=models.BooleanField(default=False, validators=[apps.iamstudent.models.validate_checkbox]),
        ),
        migrations.AddField(
            model_name='student',
            name='wunsch_ort_apotheke',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='wunsch_ort_ueberall',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='availability_start',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
