# Generated by Django 3.0.4 on 2020-04-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0013_emailtosend_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtohospital',
            name='send_date',
            field=models.DateTimeField(null=True),
        ),
    ]
