# Generated by Django 3.0.4 on 2020-03-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0014_auto_20200326_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_medstud_abschnitt',
        ),
        migrations.RemoveField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_mfa_abschnitt',
        ),
        migrations.RemoveField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_mta_abschnitt',
        ),
        migrations.RemoveField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_mtla_abschnitt',
        ),
        migrations.RemoveField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_notfallsani_abschnitt',
        ),
        migrations.RemoveField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_pflege_abschnitt',
        ),
        migrations.RemoveField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_physio_abschnitt',
        ),
        migrations.RemoveField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_zahni_abschnitt',
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_medstud_abschnitt_gt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Vorklinischer Teil (1.-5. Semester)'), (2, 'Klinischer Teil (6.-10. Semester)'), (3, 'Praktisches Jahr'), (4, 'Assistenzarzt'), (5, 'Facharzt')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_medstud_abschnitt_lt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Vorklinischer Teil (1.-5. Semester)'), (2, 'Klinischer Teil (6.-10. Semester)'), (3, 'Praktisches Jahr'), (4, 'Assistenzarzt'), (5, 'Facharzt')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_mfa_abschnitt_gt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_mfa_abschnitt_lt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_mta_abschnitt_gt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_mta_abschnitt_lt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_mtla_abschnitt_gt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_mtla_abschnitt_lt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_notfallsani_abschnitt_gt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_notfallsani_abschnitt_lt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_pflege_abschnitt_gt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_pflege_abschnitt_lt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_physio_abschnitt_gt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_physio_abschnitt_lt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, '1. Jahr'), (2, '2. Jahr'), (3, '3. Jahr'), (4, 'Berufstätig')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_zahni_abschnitt_gt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Vorklinischer Teil'), (2, 'Klinischer Teil'), (3, 'Abgeschlossen')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='persistenstudentfiltermodel',
            name='ausbildung_typ_zahni_abschnitt_lt',
            field=models.IntegerField(choices=[(0, 'Keine Angabe'), (1, 'Vorklinischer Teil'), (2, 'Klinischer Teil'), (3, 'Abgeschlossen')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='braucht_bezahlung',
            field=models.IntegerField(choices=[(2, 'Ich freue mich über eine Vergütung, helfe aber auch ohne'), (1, 'Ich benötige eine Vergütung')], default=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='unterkunft_gewuenscht',
            field=models.BooleanField(default=False),
        ),
    ]
