# Generated by Django 3.0.4 on 2020-04-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0015_custom_migration_timestamps'),
    ]
