# Generated by Django 3.0.5 on 2020-05-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0016_auto_20200409_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='braucht_bezahlung',
            field=models.IntegerField(choices=[(2, 'Ich freue mich über eine Vergütung, helfe aber auch ohne'), (1, 'Ich benötige eine Vergütung'), (3, 'Ich möchte ohne Bezahlung helfen')], default=2),
        ),
        migrations.AlterField(
            model_name='studentlistfiltermodel',
            name='braucht_bezahlung',
            field=models.IntegerField(choices=[('', 'wissen wir nicht'), (1, 'ja'), (2, 'nein'), (3, 'individuell absprechbar')], default=0),
        ),
    ]
