# Generated by Django 3.0.5 on 2020-06-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamstudent', '0018_auto_20200522_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='datenschutz_zugestimmt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='einwilligung_agb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='einwilligung_datenweitergabe',
            field=models.BooleanField(default=False),
        ),
    ]
